### ISSUE TITLE
Bug: Only CMake versions up to 3.19.8 are downloaded

### ISSUE THREAD

**Issue by RobinGjolstad** [nlohmann/cmake_min_version#5]
From CMake version 3.20 and up, the Linux tarballs are renamed from `cmake-3.XX.XX-Linux-x86_64.tar.gz` to `cmake-3.XX.XX-linux-x86_64.tar.gz`.  
The difference in casing causes `create_version_dict()` in [cmake_downloader.py](https://github.com/nlohmann/cmake_min_version/blob/master/cmake_downloader.py) to not find newer CMake versions.

**Comment by nlohmann** [comment]
Thanks for reporting!
